<?php

/**
 * Basequests
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $uuid
 * @property string $name
 * @property string $description
 * @property string $location
 * @property string $items
 * @property integer $item_chance
 * @property string $monster
 * @property integer $monster_chance
 * @property string $status
 * @property string $party_id
 * @property timestamp $creation
 * @property timestamp $expires
 * 
 * @method integer   getId()             Returns the current record's "id" value
 * @method string    getUuid()           Returns the current record's "uuid" value
 * @method string    getName()           Returns the current record's "name" value
 * @method string    getDescription()    Returns the current record's "description" value
 * @method string    getLocation()       Returns the current record's "location" value
 * @method string    getItems()          Returns the current record's "items" value
 * @method integer   getItemChance()     Returns the current record's "item_chance" value
 * @method string    getMonster()        Returns the current record's "monster" value
 * @method integer   getMonsterChance()  Returns the current record's "monster_chance" value
 * @method string    getStatus()         Returns the current record's "status" value
 * @method string    getPartyId()        Returns the current record's "party_id" value
 * @method timestamp getCreation()       Returns the current record's "creation" value
 * @method timestamp getExpires()        Returns the current record's "expires" value
 * @method quests    setId()             Sets the current record's "id" value
 * @method quests    setUuid()           Sets the current record's "uuid" value
 * @method quests    setName()           Sets the current record's "name" value
 * @method quests    setDescription()    Sets the current record's "description" value
 * @method quests    setLocation()       Sets the current record's "location" value
 * @method quests    setItems()          Sets the current record's "items" value
 * @method quests    setItemChance()     Sets the current record's "item_chance" value
 * @method quests    setMonster()        Sets the current record's "monster" value
 * @method quests    setMonsterChance()  Sets the current record's "monster_chance" value
 * @method quests    setStatus()         Sets the current record's "status" value
 * @method quests    setPartyId()        Sets the current record's "party_id" value
 * @method quests    setCreation()       Sets the current record's "creation" value
 * @method quests    setExpires()        Sets the current record's "expires" value
 * 
 * @package    Family-Quest
 * @subpackage model
 * @author     Ralph Dittrich kizetsu.rd@googlemail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basequests extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('quests');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unique' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('uuid', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => false,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'unique' => false,
             'length' => 255,
             ));
        $this->hasColumn('location', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'unique' => false,
             'length' => 255,
             ));
        $this->hasColumn('items', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'unique' => false,
             'length' => 255,
             ));
        $this->hasColumn('item_chance', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             'unique' => false,
             ));
        $this->hasColumn('monster', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'unique' => false,
             'length' => 255,
             ));
        $this->hasColumn('monster_chance', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             'unique' => false,
             ));
        $this->hasColumn('status', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'unique' => false,
             'length' => 255,
             ));
        $this->hasColumn('party_id', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'unique' => false,
             'length' => 255,
             ));
        $this->hasColumn('creation', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('expires', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}