<?php

/**
 * Basecharacter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $uuid
 * @property string $name
 * @property integer $user_id
 * @property integer $party_id
 * @property boolean $blocked
 * @property timestamp $creation
 * 
 * @method integer   getId()       Returns the current record's "id" value
 * @method string    getUuid()     Returns the current record's "uuid" value
 * @method string    getName()     Returns the current record's "name" value
 * @method integer   getUserId()   Returns the current record's "user_id" value
 * @method integer   getPartyId()  Returns the current record's "party_id" value
 * @method boolean   getBlocked()  Returns the current record's "blocked" value
 * @method timestamp getCreation() Returns the current record's "creation" value
 * @method character setId()       Sets the current record's "id" value
 * @method character setUuid()     Sets the current record's "uuid" value
 * @method character setName()     Sets the current record's "name" value
 * @method character setUserId()   Sets the current record's "user_id" value
 * @method character setPartyId()  Sets the current record's "party_id" value
 * @method character setBlocked()  Sets the current record's "blocked" value
 * @method character setCreation() Sets the current record's "creation" value
 * 
 * @package    Family-Quest
 * @subpackage model
 * @author     Ralph Dittrich kizetsu.rd@googlemail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecharacter extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('character');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unique' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('uuid', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => true,
             ));
        $this->hasColumn('party_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => true,
             ));
        $this->hasColumn('blocked', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('creation', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}