<?php

/**
 * Basemonster
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $uuid
 * @property string $name
 * @property string $description
 * @property string $party_id
 * @property timestamp $creation
 * 
 * @method integer   getId()          Returns the current record's "id" value
 * @method string    getUuid()        Returns the current record's "uuid" value
 * @method string    getName()        Returns the current record's "name" value
 * @method string    getDescription() Returns the current record's "description" value
 * @method string    getPartyId()     Returns the current record's "party_id" value
 * @method timestamp getCreation()    Returns the current record's "creation" value
 * @method monster   setId()          Sets the current record's "id" value
 * @method monster   setUuid()        Sets the current record's "uuid" value
 * @method monster   setName()        Sets the current record's "name" value
 * @method monster   setDescription() Sets the current record's "description" value
 * @method monster   setPartyId()     Sets the current record's "party_id" value
 * @method monster   setCreation()    Sets the current record's "creation" value
 * 
 * @package    Family-Quest
 * @subpackage model
 * @author     Ralph Dittrich kizetsu.rd@googlemail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basemonster extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('monster');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unique' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('uuid', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => false,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'unique' => false,
             'length' => 255,
             ));
        $this->hasColumn('party_id', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'unique' => false,
             'length' => 255,
             ));
        $this->hasColumn('creation', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}