<?php

/**
 * Baseparty
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $uuid
 * @property string $name
 * @property integer $admin_id
 * @property timestamp $creation
 * 
 * @method integer   getId()       Returns the current record's "id" value
 * @method string    getUuid()     Returns the current record's "uuid" value
 * @method string    getName()     Returns the current record's "name" value
 * @method integer   getAdminId()  Returns the current record's "admin_id" value
 * @method timestamp getCreation() Returns the current record's "creation" value
 * @method party     setId()       Sets the current record's "id" value
 * @method party     setUuid()     Sets the current record's "uuid" value
 * @method party     setName()     Sets the current record's "name" value
 * @method party     setAdminId()  Sets the current record's "admin_id" value
 * @method party     setCreation() Sets the current record's "creation" value
 * 
 * @package    Family-Quest
 * @subpackage model
 * @author     Ralph Dittrich kizetsu.rd@googlemail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseparty extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('party');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unique' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('uuid', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('admin_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => false,
             ));
        $this->hasColumn('creation', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}