<?php

/**
 * Basegroups
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $uuid
 * @property string $groupname
 * @property string $description
 * @property timestamp $creation
 * 
 * @method integer   getId()          Returns the current record's "id" value
 * @method string    getUuid()        Returns the current record's "uuid" value
 * @method string    getGroupname()   Returns the current record's "groupname" value
 * @method string    getDescription() Returns the current record's "description" value
 * @method timestamp getCreation()    Returns the current record's "creation" value
 * @method groups    setId()          Sets the current record's "id" value
 * @method groups    setUuid()        Sets the current record's "uuid" value
 * @method groups    setGroupname()   Sets the current record's "groupname" value
 * @method groups    setDescription() Sets the current record's "description" value
 * @method groups    setCreation()    Sets the current record's "creation" value
 * 
 * @package    Family-Quest
 * @subpackage model
 * @author     Ralph Dittrich kizetsu.rd@googlemail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basegroups extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('groups');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unique' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('uuid', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('groupname', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('creation', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}