<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/03/05 00:12:03

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'pgsql:host=localhost;dbname=familyquest',
  'username' => 'postgres',
  'password' => 'postgres',
  'name' => 'doctrine',
)),);
