<?php

/**
 * groupsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class groupsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object groupsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('groups');
    }
}