<?php

/**
 * itemsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class itemsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object itemsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('items');
    }
}