<?php

/**
 * monsterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class monsterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object monsterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('monster');
    }
}