<?php

/**
 * monster
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Family-Quest
 * @subpackage model
 * @author     Ralph Dittrich kizetsu.rd@googlemail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class monster extends Basemonster
{
}
