<?php

/**
 * partyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class partyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object partyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('party');
    }
}