<?php

/**
 * questsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class questsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object questsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('quests');
    }
}