<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/03/01 22:45:16

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'pgsql:host=localhost;dbname=familyquest',
  'username' => 'postgres',
  'password' => 'postgres',
  'name' => 'doctrine',
)),);
